services:
  nginx:
    build :
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build :
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  mariadb:
    build :
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
    - .env
    volumes:
      - ./database:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      inception:

networks:
  inception:
