services:
  nginx:
    build :
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image : nginx
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - /Users/koseki.yusuke/ykoseki/data/wordpress:/var/www/html
    networks:
      inception:
  wordpress:
    build :
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image : wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    secrets:
      - credentials
    volumes:
      - /Users/koseki.yusuke/ykoseki/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_REDIS_HOST=redis
    networks:
      inception:
  mariadb:
    build :
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image : mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - /Users/koseki.yusuke/ykoseki/data/mariadb:/var/lib/mysql
      - ./requirements/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      inception:

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image : adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      inception:  
  
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      inception:

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image : ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - /Users/koseki.yusuke/ykoseki/data/wordpress:/var/www/html
    networks:
      inception:

networks:
  inception:

secrets:
    db_password:
      file: ./secrets/db_password.txt
    db_root_password:
      file: ./secrets/db_root_password.txt
    credentials:
      file: ./secrets/credentials.txt
